/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings/permissions'
import { Route as AuthenticatedSettingsHospitalRouteImport } from './routes/_authenticated/settings/hospital'
import { Route as AuthenticatedRadiologyXrayRouteImport } from './routes/_authenticated/radiology/xray'
import { Route as AuthenticatedRadiologyReportsRouteImport } from './routes/_authenticated/radiology/reports'
import { Route as AuthenticatedRadiologyMriRouteImport } from './routes/_authenticated/radiology/mri'
import { Route as AuthenticatedRadiologyCtRouteImport } from './routes/_authenticated/radiology/ct'
import { Route as AuthenticatedPharmacyStockRouteImport } from './routes/_authenticated/pharmacy/stock'
import { Route as AuthenticatedPharmacySalesRouteImport } from './routes/_authenticated/pharmacy/sales'
import { Route as AuthenticatedPharmacyInventoryRouteImport } from './routes/_authenticated/pharmacy/inventory'
import { Route as AuthenticatedOpdTokensRouteImport } from './routes/_authenticated/opd/tokens'
import { Route as AuthenticatedOpdRegistrationRouteImport } from './routes/_authenticated/opd/registration'
import { Route as AuthenticatedOpdQueueRouteImport } from './routes/_authenticated/opd/queue'
import { Route as AuthenticatedOpdPrescriptionsRouteImport } from './routes/_authenticated/opd/prescriptions'
import { Route as AuthenticatedOpdEmrRouteImport } from './routes/_authenticated/opd/emr'
import { Route as AuthenticatedOpdCertificatesRouteImport } from './routes/_authenticated/opd/certificates'
import { Route as AuthenticatedOpdAppointmentsRouteImport } from './routes/_authenticated/opd/appointments'
import { Route as AuthenticatedLabSamplesRouteImport } from './routes/_authenticated/lab/samples'
import { Route as AuthenticatedLabReportsRouteImport } from './routes/_authenticated/lab/reports'
import { Route as AuthenticatedLabBookingRouteImport } from './routes/_authenticated/lab/booking'
import { Route as AuthenticatedIpdNursingRouteImport } from './routes/_authenticated/ipd/nursing'
import { Route as AuthenticatedIpdDischargeRouteImport } from './routes/_authenticated/ipd/discharge'
import { Route as AuthenticatedIpdBedsRouteImport } from './routes/_authenticated/ipd/beds'
import { Route as AuthenticatedIpdAdmissionRouteImport } from './routes/_authenticated/ipd/admission'
import { Route as AuthenticatedHrStaffRouteImport } from './routes/_authenticated/hr/staff'
import { Route as AuthenticatedHrPayrollRouteImport } from './routes/_authenticated/hr/payroll'
import { Route as AuthenticatedHrAttendanceRouteImport } from './routes/_authenticated/hr/attendance'
import { Route as AuthenticatedBillingOpdRouteImport } from './routes/_authenticated/billing/opd'
import { Route as AuthenticatedBillingIpdRouteImport } from './routes/_authenticated/billing/ipd'
import { Route as AuthenticatedBillingExpensesRouteImport } from './routes/_authenticated/billing/expenses'
import { Route as AuthenticatedBillingDoctorShareRouteImport } from './routes/_authenticated/billing/doctor-share'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsHospitalRoute =
  AuthenticatedSettingsHospitalRouteImport.update({
    id: '/settings/hospital',
    path: '/settings/hospital',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRadiologyXrayRoute =
  AuthenticatedRadiologyXrayRouteImport.update({
    id: '/radiology/xray',
    path: '/radiology/xray',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRadiologyReportsRoute =
  AuthenticatedRadiologyReportsRouteImport.update({
    id: '/radiology/reports',
    path: '/radiology/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRadiologyMriRoute =
  AuthenticatedRadiologyMriRouteImport.update({
    id: '/radiology/mri',
    path: '/radiology/mri',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRadiologyCtRoute =
  AuthenticatedRadiologyCtRouteImport.update({
    id: '/radiology/ct',
    path: '/radiology/ct',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyStockRoute =
  AuthenticatedPharmacyStockRouteImport.update({
    id: '/pharmacy/stock',
    path: '/pharmacy/stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacySalesRoute =
  AuthenticatedPharmacySalesRouteImport.update({
    id: '/pharmacy/sales',
    path: '/pharmacy/sales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPharmacyInventoryRoute =
  AuthenticatedPharmacyInventoryRouteImport.update({
    id: '/pharmacy/inventory',
    path: '/pharmacy/inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpdTokensRoute = AuthenticatedOpdTokensRouteImport.update({
  id: '/opd/tokens',
  path: '/opd/tokens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpdRegistrationRoute =
  AuthenticatedOpdRegistrationRouteImport.update({
    id: '/opd/registration',
    path: '/opd/registration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpdQueueRoute = AuthenticatedOpdQueueRouteImport.update({
  id: '/opd/queue',
  path: '/opd/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpdPrescriptionsRoute =
  AuthenticatedOpdPrescriptionsRouteImport.update({
    id: '/opd/prescriptions',
    path: '/opd/prescriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpdEmrRoute = AuthenticatedOpdEmrRouteImport.update({
  id: '/opd/emr',
  path: '/opd/emr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpdCertificatesRoute =
  AuthenticatedOpdCertificatesRouteImport.update({
    id: '/opd/certificates',
    path: '/opd/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOpdAppointmentsRoute =
  AuthenticatedOpdAppointmentsRouteImport.update({
    id: '/opd/appointments',
    path: '/opd/appointments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabSamplesRoute = AuthenticatedLabSamplesRouteImport.update({
  id: '/lab/samples',
  path: '/lab/samples',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabReportsRoute = AuthenticatedLabReportsRouteImport.update({
  id: '/lab/reports',
  path: '/lab/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLabBookingRoute = AuthenticatedLabBookingRouteImport.update({
  id: '/lab/booking',
  path: '/lab/booking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpdNursingRoute = AuthenticatedIpdNursingRouteImport.update({
  id: '/ipd/nursing',
  path: '/ipd/nursing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpdDischargeRoute =
  AuthenticatedIpdDischargeRouteImport.update({
    id: '/ipd/discharge',
    path: '/ipd/discharge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIpdBedsRoute = AuthenticatedIpdBedsRouteImport.update({
  id: '/ipd/beds',
  path: '/ipd/beds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIpdAdmissionRoute =
  AuthenticatedIpdAdmissionRouteImport.update({
    id: '/ipd/admission',
    path: '/ipd/admission',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrStaffRoute = AuthenticatedHrStaffRouteImport.update({
  id: '/hr/staff',
  path: '/hr/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrPayrollRoute = AuthenticatedHrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrAttendanceRoute =
  AuthenticatedHrAttendanceRouteImport.update({
    id: '/hr/attendance',
    path: '/hr/attendance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingOpdRoute = AuthenticatedBillingOpdRouteImport.update({
  id: '/billing/opd',
  path: '/billing/opd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingIpdRoute = AuthenticatedBillingIpdRouteImport.update({
  id: '/billing/ipd',
  path: '/billing/ipd',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingExpensesRoute =
  AuthenticatedBillingExpensesRouteImport.update({
    id: '/billing/expenses',
    path: '/billing/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingDoctorShareRoute =
  AuthenticatedBillingDoctorShareRouteImport.update({
    id: '/billing/doctor-share',
    path: '/billing/doctor-share',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/billing/doctor-share': typeof AuthenticatedBillingDoctorShareRoute
  '/billing/expenses': typeof AuthenticatedBillingExpensesRoute
  '/billing/ipd': typeof AuthenticatedBillingIpdRoute
  '/billing/opd': typeof AuthenticatedBillingOpdRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/staff': typeof AuthenticatedHrStaffRoute
  '/ipd/admission': typeof AuthenticatedIpdAdmissionRoute
  '/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/ipd/discharge': typeof AuthenticatedIpdDischargeRoute
  '/ipd/nursing': typeof AuthenticatedIpdNursingRoute
  '/lab/booking': typeof AuthenticatedLabBookingRoute
  '/lab/reports': typeof AuthenticatedLabReportsRoute
  '/lab/samples': typeof AuthenticatedLabSamplesRoute
  '/opd/appointments': typeof AuthenticatedOpdAppointmentsRoute
  '/opd/certificates': typeof AuthenticatedOpdCertificatesRoute
  '/opd/emr': typeof AuthenticatedOpdEmrRoute
  '/opd/prescriptions': typeof AuthenticatedOpdPrescriptionsRoute
  '/opd/queue': typeof AuthenticatedOpdQueueRoute
  '/opd/registration': typeof AuthenticatedOpdRegistrationRoute
  '/opd/tokens': typeof AuthenticatedOpdTokensRoute
  '/pharmacy/inventory': typeof AuthenticatedPharmacyInventoryRoute
  '/pharmacy/sales': typeof AuthenticatedPharmacySalesRoute
  '/pharmacy/stock': typeof AuthenticatedPharmacyStockRoute
  '/radiology/ct': typeof AuthenticatedRadiologyCtRoute
  '/radiology/mri': typeof AuthenticatedRadiologyMriRoute
  '/radiology/reports': typeof AuthenticatedRadiologyReportsRoute
  '/radiology/xray': typeof AuthenticatedRadiologyXrayRoute
  '/settings/hospital': typeof AuthenticatedSettingsHospitalRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/billing/doctor-share': typeof AuthenticatedBillingDoctorShareRoute
  '/billing/expenses': typeof AuthenticatedBillingExpensesRoute
  '/billing/ipd': typeof AuthenticatedBillingIpdRoute
  '/billing/opd': typeof AuthenticatedBillingOpdRoute
  '/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/hr/staff': typeof AuthenticatedHrStaffRoute
  '/ipd/admission': typeof AuthenticatedIpdAdmissionRoute
  '/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/ipd/discharge': typeof AuthenticatedIpdDischargeRoute
  '/ipd/nursing': typeof AuthenticatedIpdNursingRoute
  '/lab/booking': typeof AuthenticatedLabBookingRoute
  '/lab/reports': typeof AuthenticatedLabReportsRoute
  '/lab/samples': typeof AuthenticatedLabSamplesRoute
  '/opd/appointments': typeof AuthenticatedOpdAppointmentsRoute
  '/opd/certificates': typeof AuthenticatedOpdCertificatesRoute
  '/opd/emr': typeof AuthenticatedOpdEmrRoute
  '/opd/prescriptions': typeof AuthenticatedOpdPrescriptionsRoute
  '/opd/queue': typeof AuthenticatedOpdQueueRoute
  '/opd/registration': typeof AuthenticatedOpdRegistrationRoute
  '/opd/tokens': typeof AuthenticatedOpdTokensRoute
  '/pharmacy/inventory': typeof AuthenticatedPharmacyInventoryRoute
  '/pharmacy/sales': typeof AuthenticatedPharmacySalesRoute
  '/pharmacy/stock': typeof AuthenticatedPharmacyStockRoute
  '/radiology/ct': typeof AuthenticatedRadiologyCtRoute
  '/radiology/mri': typeof AuthenticatedRadiologyMriRoute
  '/radiology/reports': typeof AuthenticatedRadiologyReportsRoute
  '/radiology/xray': typeof AuthenticatedRadiologyXrayRoute
  '/settings/hospital': typeof AuthenticatedSettingsHospitalRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/billing/doctor-share': typeof AuthenticatedBillingDoctorShareRoute
  '/_authenticated/billing/expenses': typeof AuthenticatedBillingExpensesRoute
  '/_authenticated/billing/ipd': typeof AuthenticatedBillingIpdRoute
  '/_authenticated/billing/opd': typeof AuthenticatedBillingOpdRoute
  '/_authenticated/hr/attendance': typeof AuthenticatedHrAttendanceRoute
  '/_authenticated/hr/payroll': typeof AuthenticatedHrPayrollRoute
  '/_authenticated/hr/staff': typeof AuthenticatedHrStaffRoute
  '/_authenticated/ipd/admission': typeof AuthenticatedIpdAdmissionRoute
  '/_authenticated/ipd/beds': typeof AuthenticatedIpdBedsRoute
  '/_authenticated/ipd/discharge': typeof AuthenticatedIpdDischargeRoute
  '/_authenticated/ipd/nursing': typeof AuthenticatedIpdNursingRoute
  '/_authenticated/lab/booking': typeof AuthenticatedLabBookingRoute
  '/_authenticated/lab/reports': typeof AuthenticatedLabReportsRoute
  '/_authenticated/lab/samples': typeof AuthenticatedLabSamplesRoute
  '/_authenticated/opd/appointments': typeof AuthenticatedOpdAppointmentsRoute
  '/_authenticated/opd/certificates': typeof AuthenticatedOpdCertificatesRoute
  '/_authenticated/opd/emr': typeof AuthenticatedOpdEmrRoute
  '/_authenticated/opd/prescriptions': typeof AuthenticatedOpdPrescriptionsRoute
  '/_authenticated/opd/queue': typeof AuthenticatedOpdQueueRoute
  '/_authenticated/opd/registration': typeof AuthenticatedOpdRegistrationRoute
  '/_authenticated/opd/tokens': typeof AuthenticatedOpdTokensRoute
  '/_authenticated/pharmacy/inventory': typeof AuthenticatedPharmacyInventoryRoute
  '/_authenticated/pharmacy/sales': typeof AuthenticatedPharmacySalesRoute
  '/_authenticated/pharmacy/stock': typeof AuthenticatedPharmacyStockRoute
  '/_authenticated/radiology/ct': typeof AuthenticatedRadiologyCtRoute
  '/_authenticated/radiology/mri': typeof AuthenticatedRadiologyMriRoute
  '/_authenticated/radiology/reports': typeof AuthenticatedRadiologyReportsRoute
  '/_authenticated/radiology/xray': typeof AuthenticatedRadiologyXrayRoute
  '/_authenticated/settings/hospital': typeof AuthenticatedSettingsHospitalRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/reports'
    | '/billing/doctor-share'
    | '/billing/expenses'
    | '/billing/ipd'
    | '/billing/opd'
    | '/hr/attendance'
    | '/hr/payroll'
    | '/hr/staff'
    | '/ipd/admission'
    | '/ipd/beds'
    | '/ipd/discharge'
    | '/ipd/nursing'
    | '/lab/booking'
    | '/lab/reports'
    | '/lab/samples'
    | '/opd/appointments'
    | '/opd/certificates'
    | '/opd/emr'
    | '/opd/prescriptions'
    | '/opd/queue'
    | '/opd/registration'
    | '/opd/tokens'
    | '/pharmacy/inventory'
    | '/pharmacy/sales'
    | '/pharmacy/stock'
    | '/radiology/ct'
    | '/radiology/mri'
    | '/radiology/reports'
    | '/radiology/xray'
    | '/settings/hospital'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/analytics'
    | '/dashboard'
    | '/reports'
    | '/billing/doctor-share'
    | '/billing/expenses'
    | '/billing/ipd'
    | '/billing/opd'
    | '/hr/attendance'
    | '/hr/payroll'
    | '/hr/staff'
    | '/ipd/admission'
    | '/ipd/beds'
    | '/ipd/discharge'
    | '/ipd/nursing'
    | '/lab/booking'
    | '/lab/reports'
    | '/lab/samples'
    | '/opd/appointments'
    | '/opd/certificates'
    | '/opd/emr'
    | '/opd/prescriptions'
    | '/opd/queue'
    | '/opd/registration'
    | '/opd/tokens'
    | '/pharmacy/inventory'
    | '/pharmacy/sales'
    | '/pharmacy/stock'
    | '/radiology/ct'
    | '/radiology/mri'
    | '/radiology/reports'
    | '/radiology/xray'
    | '/settings/hospital'
    | '/settings/permissions'
    | '/settings/roles'
    | '/settings/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/billing/doctor-share'
    | '/_authenticated/billing/expenses'
    | '/_authenticated/billing/ipd'
    | '/_authenticated/billing/opd'
    | '/_authenticated/hr/attendance'
    | '/_authenticated/hr/payroll'
    | '/_authenticated/hr/staff'
    | '/_authenticated/ipd/admission'
    | '/_authenticated/ipd/beds'
    | '/_authenticated/ipd/discharge'
    | '/_authenticated/ipd/nursing'
    | '/_authenticated/lab/booking'
    | '/_authenticated/lab/reports'
    | '/_authenticated/lab/samples'
    | '/_authenticated/opd/appointments'
    | '/_authenticated/opd/certificates'
    | '/_authenticated/opd/emr'
    | '/_authenticated/opd/prescriptions'
    | '/_authenticated/opd/queue'
    | '/_authenticated/opd/registration'
    | '/_authenticated/opd/tokens'
    | '/_authenticated/pharmacy/inventory'
    | '/_authenticated/pharmacy/sales'
    | '/_authenticated/pharmacy/stock'
    | '/_authenticated/radiology/ct'
    | '/_authenticated/radiology/mri'
    | '/_authenticated/radiology/reports'
    | '/_authenticated/radiology/xray'
    | '/_authenticated/settings/hospital'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/hospital': {
      id: '/_authenticated/settings/hospital'
      path: '/settings/hospital'
      fullPath: '/settings/hospital'
      preLoaderRoute: typeof AuthenticatedSettingsHospitalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radiology/xray': {
      id: '/_authenticated/radiology/xray'
      path: '/radiology/xray'
      fullPath: '/radiology/xray'
      preLoaderRoute: typeof AuthenticatedRadiologyXrayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radiology/reports': {
      id: '/_authenticated/radiology/reports'
      path: '/radiology/reports'
      fullPath: '/radiology/reports'
      preLoaderRoute: typeof AuthenticatedRadiologyReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radiology/mri': {
      id: '/_authenticated/radiology/mri'
      path: '/radiology/mri'
      fullPath: '/radiology/mri'
      preLoaderRoute: typeof AuthenticatedRadiologyMriRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radiology/ct': {
      id: '/_authenticated/radiology/ct'
      path: '/radiology/ct'
      fullPath: '/radiology/ct'
      preLoaderRoute: typeof AuthenticatedRadiologyCtRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/stock': {
      id: '/_authenticated/pharmacy/stock'
      path: '/pharmacy/stock'
      fullPath: '/pharmacy/stock'
      preLoaderRoute: typeof AuthenticatedPharmacyStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/sales': {
      id: '/_authenticated/pharmacy/sales'
      path: '/pharmacy/sales'
      fullPath: '/pharmacy/sales'
      preLoaderRoute: typeof AuthenticatedPharmacySalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pharmacy/inventory': {
      id: '/_authenticated/pharmacy/inventory'
      path: '/pharmacy/inventory'
      fullPath: '/pharmacy/inventory'
      preLoaderRoute: typeof AuthenticatedPharmacyInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/tokens': {
      id: '/_authenticated/opd/tokens'
      path: '/opd/tokens'
      fullPath: '/opd/tokens'
      preLoaderRoute: typeof AuthenticatedOpdTokensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/registration': {
      id: '/_authenticated/opd/registration'
      path: '/opd/registration'
      fullPath: '/opd/registration'
      preLoaderRoute: typeof AuthenticatedOpdRegistrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/queue': {
      id: '/_authenticated/opd/queue'
      path: '/opd/queue'
      fullPath: '/opd/queue'
      preLoaderRoute: typeof AuthenticatedOpdQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/prescriptions': {
      id: '/_authenticated/opd/prescriptions'
      path: '/opd/prescriptions'
      fullPath: '/opd/prescriptions'
      preLoaderRoute: typeof AuthenticatedOpdPrescriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/emr': {
      id: '/_authenticated/opd/emr'
      path: '/opd/emr'
      fullPath: '/opd/emr'
      preLoaderRoute: typeof AuthenticatedOpdEmrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/certificates': {
      id: '/_authenticated/opd/certificates'
      path: '/opd/certificates'
      fullPath: '/opd/certificates'
      preLoaderRoute: typeof AuthenticatedOpdCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opd/appointments': {
      id: '/_authenticated/opd/appointments'
      path: '/opd/appointments'
      fullPath: '/opd/appointments'
      preLoaderRoute: typeof AuthenticatedOpdAppointmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/samples': {
      id: '/_authenticated/lab/samples'
      path: '/lab/samples'
      fullPath: '/lab/samples'
      preLoaderRoute: typeof AuthenticatedLabSamplesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/reports': {
      id: '/_authenticated/lab/reports'
      path: '/lab/reports'
      fullPath: '/lab/reports'
      preLoaderRoute: typeof AuthenticatedLabReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lab/booking': {
      id: '/_authenticated/lab/booking'
      path: '/lab/booking'
      fullPath: '/lab/booking'
      preLoaderRoute: typeof AuthenticatedLabBookingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipd/nursing': {
      id: '/_authenticated/ipd/nursing'
      path: '/ipd/nursing'
      fullPath: '/ipd/nursing'
      preLoaderRoute: typeof AuthenticatedIpdNursingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipd/discharge': {
      id: '/_authenticated/ipd/discharge'
      path: '/ipd/discharge'
      fullPath: '/ipd/discharge'
      preLoaderRoute: typeof AuthenticatedIpdDischargeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipd/beds': {
      id: '/_authenticated/ipd/beds'
      path: '/ipd/beds'
      fullPath: '/ipd/beds'
      preLoaderRoute: typeof AuthenticatedIpdBedsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ipd/admission': {
      id: '/_authenticated/ipd/admission'
      path: '/ipd/admission'
      fullPath: '/ipd/admission'
      preLoaderRoute: typeof AuthenticatedIpdAdmissionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/staff': {
      id: '/_authenticated/hr/staff'
      path: '/hr/staff'
      fullPath: '/hr/staff'
      preLoaderRoute: typeof AuthenticatedHrStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/payroll': {
      id: '/_authenticated/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof AuthenticatedHrPayrollRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/attendance': {
      id: '/_authenticated/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof AuthenticatedHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/opd': {
      id: '/_authenticated/billing/opd'
      path: '/billing/opd'
      fullPath: '/billing/opd'
      preLoaderRoute: typeof AuthenticatedBillingOpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/ipd': {
      id: '/_authenticated/billing/ipd'
      path: '/billing/ipd'
      fullPath: '/billing/ipd'
      preLoaderRoute: typeof AuthenticatedBillingIpdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/expenses': {
      id: '/_authenticated/billing/expenses'
      path: '/billing/expenses'
      fullPath: '/billing/expenses'
      preLoaderRoute: typeof AuthenticatedBillingExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/doctor-share': {
      id: '/_authenticated/billing/doctor-share'
      path: '/billing/doctor-share'
      fullPath: '/billing/doctor-share'
      preLoaderRoute: typeof AuthenticatedBillingDoctorShareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedBillingDoctorShareRoute: typeof AuthenticatedBillingDoctorShareRoute
  AuthenticatedBillingExpensesRoute: typeof AuthenticatedBillingExpensesRoute
  AuthenticatedBillingIpdRoute: typeof AuthenticatedBillingIpdRoute
  AuthenticatedBillingOpdRoute: typeof AuthenticatedBillingOpdRoute
  AuthenticatedHrAttendanceRoute: typeof AuthenticatedHrAttendanceRoute
  AuthenticatedHrPayrollRoute: typeof AuthenticatedHrPayrollRoute
  AuthenticatedHrStaffRoute: typeof AuthenticatedHrStaffRoute
  AuthenticatedIpdAdmissionRoute: typeof AuthenticatedIpdAdmissionRoute
  AuthenticatedIpdBedsRoute: typeof AuthenticatedIpdBedsRoute
  AuthenticatedIpdDischargeRoute: typeof AuthenticatedIpdDischargeRoute
  AuthenticatedIpdNursingRoute: typeof AuthenticatedIpdNursingRoute
  AuthenticatedLabBookingRoute: typeof AuthenticatedLabBookingRoute
  AuthenticatedLabReportsRoute: typeof AuthenticatedLabReportsRoute
  AuthenticatedLabSamplesRoute: typeof AuthenticatedLabSamplesRoute
  AuthenticatedOpdAppointmentsRoute: typeof AuthenticatedOpdAppointmentsRoute
  AuthenticatedOpdCertificatesRoute: typeof AuthenticatedOpdCertificatesRoute
  AuthenticatedOpdEmrRoute: typeof AuthenticatedOpdEmrRoute
  AuthenticatedOpdPrescriptionsRoute: typeof AuthenticatedOpdPrescriptionsRoute
  AuthenticatedOpdQueueRoute: typeof AuthenticatedOpdQueueRoute
  AuthenticatedOpdRegistrationRoute: typeof AuthenticatedOpdRegistrationRoute
  AuthenticatedOpdTokensRoute: typeof AuthenticatedOpdTokensRoute
  AuthenticatedPharmacyInventoryRoute: typeof AuthenticatedPharmacyInventoryRoute
  AuthenticatedPharmacySalesRoute: typeof AuthenticatedPharmacySalesRoute
  AuthenticatedPharmacyStockRoute: typeof AuthenticatedPharmacyStockRoute
  AuthenticatedRadiologyCtRoute: typeof AuthenticatedRadiologyCtRoute
  AuthenticatedRadiologyMriRoute: typeof AuthenticatedRadiologyMriRoute
  AuthenticatedRadiologyReportsRoute: typeof AuthenticatedRadiologyReportsRoute
  AuthenticatedRadiologyXrayRoute: typeof AuthenticatedRadiologyXrayRoute
  AuthenticatedSettingsHospitalRoute: typeof AuthenticatedSettingsHospitalRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedBillingDoctorShareRoute: AuthenticatedBillingDoctorShareRoute,
  AuthenticatedBillingExpensesRoute: AuthenticatedBillingExpensesRoute,
  AuthenticatedBillingIpdRoute: AuthenticatedBillingIpdRoute,
  AuthenticatedBillingOpdRoute: AuthenticatedBillingOpdRoute,
  AuthenticatedHrAttendanceRoute: AuthenticatedHrAttendanceRoute,
  AuthenticatedHrPayrollRoute: AuthenticatedHrPayrollRoute,
  AuthenticatedHrStaffRoute: AuthenticatedHrStaffRoute,
  AuthenticatedIpdAdmissionRoute: AuthenticatedIpdAdmissionRoute,
  AuthenticatedIpdBedsRoute: AuthenticatedIpdBedsRoute,
  AuthenticatedIpdDischargeRoute: AuthenticatedIpdDischargeRoute,
  AuthenticatedIpdNursingRoute: AuthenticatedIpdNursingRoute,
  AuthenticatedLabBookingRoute: AuthenticatedLabBookingRoute,
  AuthenticatedLabReportsRoute: AuthenticatedLabReportsRoute,
  AuthenticatedLabSamplesRoute: AuthenticatedLabSamplesRoute,
  AuthenticatedOpdAppointmentsRoute: AuthenticatedOpdAppointmentsRoute,
  AuthenticatedOpdCertificatesRoute: AuthenticatedOpdCertificatesRoute,
  AuthenticatedOpdEmrRoute: AuthenticatedOpdEmrRoute,
  AuthenticatedOpdPrescriptionsRoute: AuthenticatedOpdPrescriptionsRoute,
  AuthenticatedOpdQueueRoute: AuthenticatedOpdQueueRoute,
  AuthenticatedOpdRegistrationRoute: AuthenticatedOpdRegistrationRoute,
  AuthenticatedOpdTokensRoute: AuthenticatedOpdTokensRoute,
  AuthenticatedPharmacyInventoryRoute: AuthenticatedPharmacyInventoryRoute,
  AuthenticatedPharmacySalesRoute: AuthenticatedPharmacySalesRoute,
  AuthenticatedPharmacyStockRoute: AuthenticatedPharmacyStockRoute,
  AuthenticatedRadiologyCtRoute: AuthenticatedRadiologyCtRoute,
  AuthenticatedRadiologyMriRoute: AuthenticatedRadiologyMriRoute,
  AuthenticatedRadiologyReportsRoute: AuthenticatedRadiologyReportsRoute,
  AuthenticatedRadiologyXrayRoute: AuthenticatedRadiologyXrayRoute,
  AuthenticatedSettingsHospitalRoute: AuthenticatedSettingsHospitalRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
